import Joi from 'joi'

/**
 * Material options offered by the create-work-item form (RA-127).
 *
 * The set is the demo-friendly minimum; the backend stores the value as
 * an opaque string on the work item payload, so adding a new material
 * here is purely a frontend concern.
 */
export const MATERIAL_OPTIONS = [
  { value: 'aluminium', text: 'Aluminium' },
  { value: 'glass', text: 'Glass' },
  { value: 'paper', text: 'Paper' },
  { value: 'plastic', text: 'Plastic' },
  { value: 'steel', text: 'Steel' },
  { value: 'wood', text: 'Wood' }
]

/**
 * Tonnage band options offered by the create-work-item form (RA-127).
 *
 * `5000-plus` rather than `5000+` so the value flows through query
 * strings, JSON and Mongo without escaping surprises.
 */
export const TONNAGE_BAND_OPTIONS = [
  { value: '0-500', text: '0 to 500 tonnes' },
  { value: '500-5000', text: '500 to 5,000 tonnes' },
  { value: '5000-plus', text: '5,000+ tonnes' }
]

/**
 * Nation options offered by the create-work-item form (RA-526).
 *
 * management-be's ReAccreditationNationRoutingHook used to derive Nation
 * from the site address postcode - unreliable (postcode prefixes that
 * straddle a nation border) and, separately, dead code for real operator
 * submissions (which send siteAddress as a flat string, not the nested
 * document that derivation expected). The hook now trusts this
 * caller-supplied value directly, defaulting to England when it's absent.
 * Values must match management-be's Nation enum member names exactly.
 */
export const NATION_OPTIONS = [
  { value: 'England', text: 'England' },
  { value: 'Scotland', text: 'Scotland' },
  { value: 'Wales', text: 'Wales' },
  { value: 'NorthernIreland', text: 'Northern Ireland' }
]

const MATERIAL_VALUES = MATERIAL_OPTIONS.map((o) => o.value)
const TONNAGE_VALUES = TONNAGE_BAND_OPTIONS.map((o) => o.value)
const NATION_VALUES = NATION_OPTIONS.map((o) => o.value)

// Permissive UK postcode pattern. The full BS 7666 regex is huge and
// rejects valid edge cases (e.g. `GIR 0AA`); for the demo we only need
// to catch obvious nonsense and let the operator's real address-lookup
// do the strict validation.
const POSTCODE_PATTERN = /^[A-Z0-9 ]{3,10}$/i

/**
 * Joi schema for the create-work-item form (RA-127, re-accreditation type).
 *
 * `abortEarly: false` so the controller can render every field error in
 * one pass via `govukErrorSummary`. `stripUnknown: true` so nothing the
 * user sneaks into the form ends up in the backend payload.
 */
export const createReAccreditationSchema = Joi.object({
  // RA-219: the application reference is generated by the backend on
  // submission and is no longer an inbound form field.
  // RA-172: pre-filled, editable email captured against the work item.
  // Joi's built-in email rule is good enough for the demo; the operator's
  // real identity service will do strict checking downstream.
  operatorEmail: Joi.string()
    .trim()
    .required()
    .max(254)
    .email({ tlds: false })
    .messages({
      'any.required': 'Enter an email address',
      'string.empty': 'Enter an email address',
      'string.max': 'Email address must be 254 characters or fewer',
      'string.email':
        'Enter an email address in the correct format, like name@example.com'
    }),
  organisationName: Joi.string().trim().required().max(200).messages({
    'any.required': 'Enter the organisation name',
    'string.empty': 'Enter the organisation name',
    'string.max': 'Organisation name must be 200 characters or fewer'
  }),
  // RA-448: management-be's accreditation-number adapter requires a real,
  // numeric 6-digit Org ID to call the backend — an item created through
  // this form previously had none, which every submission now needs
  // regardless of how the work item was created (case-management form or
  // real operator journey).
  operatorOrganisationId: Joi.string()
    .trim()
    .required()
    .pattern(/^\d{6}$/)
    .messages({
      'any.required': 'Enter the organisation ID',
      'string.empty': 'Enter the organisation ID',
      'string.pattern.base': 'Organisation ID must be 6 digits'
    }),
  // RA-448: required for prior-year ReEx lookups (paired with Org ID). No
  // format constraint beyond non-blank — unlike Org ID this has no
  // universally fixed shape in the real data.
  operatorRegistrationId: Joi.string().trim().required().max(100).messages({
    'any.required': 'Enter the operator registration ID',
    'string.empty': 'Enter the operator registration ID',
    'string.max': 'Operator registration ID must be 100 characters or fewer'
  }),
  // RA-448 phase 2 review: the accreditation-number adapter's {applicationId}
  // route segment is management-be's payload.operatorApplicationId — the
  // backend's own AccreditationApplicationModel id for a real submission,
  // confirmed against HttpCaseWorkingApiAdapter.BuildPayload. It is a
  // DIFFERENT field from operatorRegistrationId above (the ReEx
  // registration id, used for prior-year lookups) — an earlier version of
  // this integration sent operatorRegistrationId here, which was wrong.
  operatorApplicationId: Joi.string().trim().required().max(100).messages({
    'any.required': 'Enter the operator application ID',
    'string.empty': 'Enter the operator application ID',
    'string.max': 'Operator application ID must be 100 characters or fewer'
  }),
  siteAddress: Joi.object({
    line1: Joi.string().trim().required().max(100).messages({
      'any.required': 'Enter the site address line 1',
      'string.empty': 'Enter the site address line 1',
      'string.max': 'Address line 1 must be 100 characters or fewer'
    }),
    line2: Joi.string().trim().allow('').max(100).messages({
      'string.max': 'Address line 2 must be 100 characters or fewer'
    }),
    town: Joi.string().trim().required().max(100).messages({
      'any.required': 'Enter the town or city',
      'string.empty': 'Enter the town or city',
      'string.max': 'Town must be 100 characters or fewer'
    }),
    postcode: Joi.string()
      .trim()
      .required()
      .max(10)
      .pattern(POSTCODE_PATTERN)
      .messages({
        'any.required': 'Enter the postcode',
        'string.empty': 'Enter the postcode',
        'string.max': 'Postcode must be 10 characters or fewer',
        'string.pattern.base': 'Enter a valid UK postcode'
      })
  })
    .required()
    .messages({ 'any.required': 'Enter the site address' }),
  material: Joi.string()
    .trim()
    .required()
    .valid(...MATERIAL_VALUES)
    .messages({
      'any.required': 'Select a material',
      'string.empty': 'Select a material',
      'any.only': 'Select a material from the list'
    }),
  tonnageBand: Joi.string()
    .trim()
    .required()
    .valid(...TONNAGE_VALUES)
    .messages({
      'any.required': 'Select a tonnage band',
      'string.empty': 'Select a tonnage band',
      'any.only': 'Select a tonnage band from the list'
    }),
  // RA-526: required so management-be's ReAccreditationNationRoutingHook has
  // a reliable value to route on - see NATION_OPTIONS above.
  nation: Joi.string()
    .trim()
    .required()
    .valid(...NATION_VALUES)
    .messages({
      'any.required': 'Select a nation',
      'string.empty': 'Select a nation',
      'any.only': 'Select a nation from the list'
    }),
  // RA-316. OPTIONAL PASSTHROUGH — plumbing, not logic.
  //
  // Exists here solely so `stripUnknown: true` stops discarding it; the
  // value is forwarded to the backend unchanged. The form can CARRY a
  // charge that someone else decides; it never computes one.
  //
  // ⚠ NO `.default()`, NO PREFILL, AND NO VALUE DERIVED FROM
  // `tonnageBand`. Empty is the normal case, not an omission to fix.
  //
  // A `.default()` here would fire for EVERY caller of this schema, and
  // `POST /work-items` is the REAL submission path — legacy-be posts
  // every genuine operator application to it, so the backend cannot tell
  // this form from production traffic.
  //
  // That matters because ABSENT IS A LEGITIMATE STATE. legacy-be drops
  // `chargeAmountPence` entirely when the tonnage band is unset, by
  // design. Defaulting on absence would put a confident, plausible,
  // FABRICATED figure in front of a regulator on the one screen whose
  // purpose is confirming money, indistinguishable from a real charge.
  // The duly-making page renders "Not provided" instead, deliberately.
  //
  // Deriving from `tonnageBand` is separately wrong: the fee table
  // already exists twice — the legacy frontend's `paymentDetails.js` and
  // the legacy backend's `AccreditationChargeCalculator` — with epr-s8k0
  // open to collapse those to one. A third copy would make case
  // management an authority on what an operator is charged, which it is
  // not, and would drift the moment fees are repriced.
  //
  // Integer PENCE, matching the wire contract — £3,276 is 327600.
  //
  // ⚠ `Joi.number()` IS LOAD-BEARING, not decoration. An HTML input always
  // posts a STRING, so without the service's `convert: true` coercion this
  // field would reach the backend as `"327600"`, land in the payload as a
  // string, and the duly-making page's formatter would return null and
  // render "Not provided" — indistinguishable from absent, with nothing
  // throwing anywhere. management-be does not validate this field (it is
  // passthrough by design), so this schema is the ONLY thing turning the
  // form's string into the integer the wire contract requires.
  chargeAmountPence: Joi.number().integer().min(0).optional().messages({
    'number.base': 'Charge amount must be a whole number of pence',
    'number.integer': 'Charge amount must be a whole number of pence',
    'number.min': 'Charge amount cannot be negative'
  })
  // RA-316. `paymentReference` is deliberately NOT an inbound field. The
  // duly-making page falls back to `applicationReference`, which is the
  // reference the operator quotes on the bank transfer and the path
  // nine-in-ten work items take, so an override field here would be
  // surface with no consumer and no test behind it.
})

/**
 * Map a Joi `ValidationError.details` array into the
 * `{ fieldId: 'message' }` shape the controller / template consume.
 *
 * Nested fields (`siteAddress.line1`) are flattened with dots so they
 * line up with the field ids in the Nunjucks template (which uses the
 * same dotted name as the form field name).
 */
export function joiDetailsToFieldErrors(details) {
  const out = {}
  for (const detail of details ?? []) {
    const path = (detail.path ?? []).join('.')
    if (path && !(path in out)) {
      out[path] = detail.message
    }
  }
  return out
}
