name: Run SonarCloud coverage scan

on:
  workflow_call:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build:
    if: github.run_number != 1 && github.actor != 'dependabot[bot]'
    name: CDP SonarCloud coverage scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install and test with coverage
        run: |
          npm ci
          npm test

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
